namespace Scriptoryum.Api.Domain.Enums;

public enum InsightCategory
{
    Risco = 0,
    Oportunidade = 1,
    Alerta = 2,
    ConformidadeRegulatoria = 3,
    Outro = 4,
    Juridico = 5,
    Financeiro = 6,
    Operacional = 7,
    Tecnico = 8,
    Contratual = 9,
    Fiscal = 10,
    Ambiental = 11,
    Social = 12,
    Governanca = 13,
    Politico = 14,
    Etico = 15,
    Reputacional = 16,
    Inovacao = 17,
    Auditoria = 18,
    Fraude = 19,
    ConflitoInteresse = 20,
    ComplianceInterno = 21,
    ComplianceExterno = 22,
    PropriedadeIntelectual = 23,
    SegurancaInformacao = 24,
    Privacidade = 25,
    RecursosHumanos = 26,
    Logistica = 27,
    Marketing = 28,
    Comercial = 29,
    Cliente = 30,
    Fornecedor = 31,
    Produto = 32,
    Servico = 33,
    Projeto = 34,
    Processo = 35,
    Evento = 36
}